import streamlit as st
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
import time
from openai import OpenAI
from google import genai
from PIL import Image
from io import BytesIO


load_dotenv()

api_key = os.getenv("GOOGLE_API_KEY")
client = genai.Client(api_key=api_key)

# functions 
def generate_album_art(user_prompt):
    if not user_prompt:
        return "Please provide a valid prompt."
    
    response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=[user_prompt],
        )
    
    for part in response.candidates[0].content.parts:
            if part.inline_data:
                # Convert the raw bytes back into a viewable image
                img = Image.open(BytesIO(part.inline_data.data))
                
                # 3. Display in Streamlit
                st.image(img, caption="Generated by Gemini 2.5 Flash Image")

def process_user_mood(mood):
    return f"Processed mood: {mood}"

# spotify setup and functions

def create_spotify_client():
     # Spotify authentication
     return

def create_user_playlist(spotify_client, mood):
    # Create a playlist based on the user's mood
    return


# main app
st.title("Audora")
st.write("Welcome to Audora! This is a simple app that uses OpenAI's API.")

with st.form("mood_form", clear_on_submit=True):
    prompt = st.text_input("Enter your prompt:")
    submitted = st.form_submit_button("Submit")

    if submitted and prompt:
        success_message = st.empty()

        success_message.text("Generating response...")

        generate_album_art(prompt)

        success_message.empty()
    else:
        st.warning("Please enter a prompt to generate album art.")
        


